// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CorpCom.Models.CorpCom
{
    [Table("Banner")]
    public partial class Banner
    {
        [Key]
        public int BannerId { get; set; }
        [StringLength(200)]
        public string PhysicalPath { get; set; }
        [StringLength(200)]
        public string ImageName { get; set; }
        [StringLength(200)]
        public string ImageUrl { get; set; }
        [StringLength(200)]
        public string LinkUrl { get; set; }
        public int? Priority { get; set; }
        public int? PositionId { get; set; }
        public bool? IsPublish { get; set; }
        [StringLength(255)]
        public string Remark { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [ForeignKey("PositionId")]
        [InverseProperty("Banners")]
        public virtual Position Position { get; set; }
    }
}